name: Deploy Quelpoke to Kubernetes

on:
  push:
    branches:
      - main  # Déploie automatiquement lorsque du code est poussé sur `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Se connecter à Google Artifact Registry (ou Docker Hub)
      run: echo "${{ secrets.d519ce9fd4a683a19c92790e08dc8e86046e22c5 }}" | docker login -u _json_key --password-stdin https://europe-west9-docker.pkg.dev

    - name: Construire et pousser l’image Docker
      run: |
        docker build -t europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-amaury/quelpoke:latest .
        docker push europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-amaury/quelpokee:latest

    - name: Déployer sur Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        KUBECONFIG=kubeconfig.yaml kubectl apply -f kube.yaml
