name: Deploy Quelpoke to Kubernetes

on:
  push:
    branches:
      - main  # Déploie automatiquement lorsque du code est poussé sur `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configurer `kubectl`
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Construire et pousser l’image Docker
      run: |
        docker build -t europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-amaury/quelpoke:latest .
        docker push europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-amaury/quelpoke:latest

    - name: Déployer sur Kubernetes
      run: |
        kubectl apply -f kube.yaml