name: Deploy Quelpoke to Kubernetes

on:
  push:
    branches:
      - main  # Déploie automatiquement lorsque du code est poussé sur `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Se connecter à Google Artifact Registry (ou Docker Hub)
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construire et pousser l’image Docker
      run: |
        docker build -t europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-hugof/quelpoke:latest .
        docker push europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-hugof/quelpoke:latest

    - name: Déployer sur Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        KUBECONFIG=kubeconfig.yaml kubectl apply -f kube.yaml
