name: Deploy Quelpoke to Kubernetes

on:
  push:
    branches:
      - main  # Déploie automatiquement lorsque du code est poussé sur `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Afficher les fichiers dans le répertoire
      run: ls -alh  # Pour vérifier les fichiers avant le build Docker

    - name: Configurer `kubectl`
      shell: bash
      env: 
        super_secret: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "$super_secret"  > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Construire et pousser l’image Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-amaury/quelpoke:latest

    - name: Déployer sur Kubernetes
      run: |
        kubectl apply -f kube.yaml
